// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PasswordController from "./password_controller.js"
application.register("password", PasswordController)

import ValidatesController from "./validates_controller.js"
application.register("validates", ValidatesController)
